### ISSUE TITLE
DelayedRender

### ISSUE THREAD

**Issue by brigand** [brigand/rearm#1]
Sometimes you have elements that aren't visible right away. You want to defer rendering these elements, while also desiring that they can be shown instantly when called for.

Real use case: there are 8 icons displayed and a "show more" button. When clicked, an additional 36 icons are displayed. Loading the extra icons on click takes real time and makes the interface seem laggy. Loading them when the always displayed icons are loaded would slow down the page load. This is a compromise that improves the initial performance, and the performance of displaying them when the "show more" is clicked.

`DelayedRender` can use one or more strategies for deciding when to render.

## Timeout

The simplest is a timeout. After X time, the element will render/mount.

```jsx
<DelayedRender strategy={{ timeout: 500 }}>
  <div style={{ display: state.showStuff ? 'block' : 'none' }}>
    <ExpensiveStuff />
  </div>
</DelayedRender>
```

## Idle

An idle callback can be registered. When the browser says nothing is going on, we render it. We can set a maximum and minimum delay before we render it.

```jsx
<DelayedRender strategy={{ idle: true, idleMin: 300, idleMax: 1000 }}>
  <div style={{ display: state.showStuff ? 'block' : 'none' }}>
    <ExpensiveStuff />
  </div>
</DelayedRender>
```

## Trigger

Often used in combination with one of the previous, a trigger can cause a load in response to an event. The trigger is its own component.

In this example we use a string literal for the `id`, but for making less assumptions, you'd use a random id created in a recent parent.

Note that we use `mouseover` as we want it to load before the button is clicked.

```jsx
<div>
  <Trigger type="DelayedRender" id="something" events={['mouseover']}>
    <button onClick={showStuff}>show more</button>
  </Trigger>
  <DelayedRender strategy={{ trigger: 'something', idle: true, idleMax: 3000 }}>
    <div style={{ display: state.showStuff ? 'block' : 'none' }}>
      <ExpensiveStuff />
    </div>
  </DelayedRender>
</div>
```

**Comment by rehat101** [comment]
This component looks unique and has potential to be added in our lib.

Should we revisit the api, now that we have hooks?

1. rename `DelayedRender` prop `strategy` to `options` perhaps?
```javascript
<DelayedRender options={...}>
<ExpensiveStuff />
</DelayedRender>
```

2. can Trigger be a hook? without type?
```javascript
const showExpensiveStuff = useTrigger({ id:'something' events:[...] });
```

**Comment by brigand** [comment]
+1 for options over strategy

Thinking about it, we can get rid of the 'id' if we produce the DelayedRender in the hook.

```jsx
const { DelayedRender, trigger } = useDelayedRender({
  idle: true,
  idleMax: 300,
}, [dependencies]);
```

The dependencies array would simply reset the active state to false when it changes


```jsx
const items = useSomeAsyncHook(
  () => getItems(props.page),
  [props.page],
);

// Starts as inactive
// Resets to inactive when 'items' changes
// Transitions to active on the idle callback (or trigger() call) after becoming
// inactive.
const { DelayedRender, trigger, isActive } = useDelayedRender({
  idle: true,
  idleMax: 300,
}, [items]);

const [ initial, rest ] = splitAt(items, 3);

return (
  <div>
    <button onClick={trigger}>Show All Now</button>
    {isActive
      ? `Displaying ${items.length}`
      : `Displaying ${initial.length}`}
    {initial.map(renderItem)}
    <DelayedRender>
      {rest.map(renderItem)}
    </DelayedRender>
  </div>
);
```

**Comment by rehat101** [comment]
Agree on producing DelayedRender in a hook.

re: Idle, do you think it make sense to use `requestIdleCallback` as tool to detect when browser is free?
