### ISSUE TITLE
Accessing PropTypes via the main React is deprecated

### ISSUE THREAD

**Issue by jeff1evesque** [brigand/rearm#11]
This package is extremely useful, and plan to continue using. However, since it's [implementation](https://github.com/jeff1evesque/machine-learning/issues/3146), the corresponding browser console, is stating *Accessing PropTypes via the main React is deprecated*:

![auth-desktop-1](https://user-images.githubusercontent.com/2907085/34180316-3a18922a-e4dc-11e7-99e6-c1d6c09ba636.JPG)

**Comment by brigand** [comment]
Thanks for the interest!

So, that's caused by `import * as React from 'react';`. It's a quirk in React 15. We're not actually using `React.PropTypes`. Could do a syntax transform to change that in the build output files.

**Comment by brigand** [comment]
Please give 0.8.1 a try.

**Comment by jeff1evesque** [comment]
Thanks, that update worked!
