### ISSUE TITLE
expand Ctx tool

### ISSUE THREAD

**Issue by rehat101** [brigand/rearm#15]
The Ctx tool is super useful when it comes to subscribing to part of the context store. 

Would love to re-think on how it can be use with Hooks.

**Comment by brigand** [comment]
My thought is something like:

```jsx
// Same as current API
import { makeCtx } from 'rearm/lib/Ctx';
const Ctx = makeCtx('some-description');

// Access in a component
function MyComp(props) {
  const something = Ctx.use(value => value.something);

  return // ...
}
```

The selector function would be optional, defaulting to the identity function (`x => x`). If the value is `===` the previous value, an update wouldn't be triggered when the context changes.

---

I'm also curious about if we need context updates without re-rendering the provider. That would require some imperative API for updating the context. It would often be beneficial for performance, but I'm not sure if it's worth the complexity.

**Comment by rehat101** [comment]
makes sense.

re: performance: we can leave that out for now.
