### ISSUE TITLE
Upgrade React version

### ISSUE THREAD

**Issue by rehat101** [brigand/rearm#16]
Upgrade the react version to the latest and check if it's breaking any changes.

**Comment by rehat101** [comment]
Should we also upgrade babel? It's quite old and the new modules are behind "@babel" scope @brigand

**Comment by brigand** [comment]
That would be good, yeah.

**Comment by rehat101** [comment]
a few plugins we don't need anymore:

1. `babel-jest` this already ships with jest so we can remove this
2. `babel-plugin-transform-object-rest-spread` - this is now supported natively in browsers, can remove this too?

**Comment by rehat101** [comment]
are we using `react-test-renderer` anywhere?
