### ISSUE TITLE
surpress componentWillReceiveProps warning

### ISSUE THREAD

**Issue by rehat101** [brigand/rearm#18]
After the update #17 
The newer version of react warns about deprecated cycle warnings. We need to remove them.

Our `Ctx` module uses the following:

```javascript
componentWillReceiveProps(nextProps: CtxProps) {
    this.update(nextProps, this.getParentState());
}
```

What would be an alternative to this? I'm going to vouch for `componentDidUpdate()`

**Comment by brigand** [comment]
I think we should change this to use a function component with hooks, but that's a bit of a significant change. I'm fine with dropping older React support. 

If we stay with the class, we should probably use getDerivedStateFromProps, but that's always a headache.

**Comment by rehat101** [comment]
closing this in ref to #19
