### ISSUE TITLE
Migrate Breakpoint to hooks

### ISSUE THREAD

**Issue by nullhook** [brigand/rearm#28]
We should migrate Breakpoint to hooks:

Rough proposal:

```javascript
const bp = useBreakpoint(breakpoints, {});

bp.isEq('small');
bp.isLt('small');
bp.isLte('small');
bp.isGte('small');
```

Do we really need an HOC here or a Render here?
If breakpoints as an option isn't given then we can fallback to defaults.

EDIT: revised as per suggestion below

**Comment by brigand** [comment]
Probably fine just taking 'breakpoints' as the first argument, and any optional parameters can be in a second object argument (I forget if there are any).

As a note, we also need to handle the case where the value of breakpoints changes within the life of the hook.

We can implement it without the render/HOC variants.
